services:
  postgres:
    image: postgres:16-alpine
    container_name: tutorial_psql_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
